spring.datasource.url=jdbc:postgresql://localhost:5432/mental_health_db
spring.datasource.username=postgres
spring.datasource.password=Ishita@2026

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect